SELECT DISTINCT * WHERE {
  ?f <http://data.linkedmdb.org/resource/movie/actor> ?a .
  ?f <http://data.linkedmdb.org/resource/movie/director> ?d .
  ?f <http://data.linkedmdb.org/resource/movie/genre> <http://data.linkedmdb.org/resource/film_genre/12> .
  ?a <http://data.linkedmdb.org/resource/movie/actor_actorid> ?aid .
  ?a <http://data.linkedmdb.org/resource/movie/actor_name> ?an .
  ?a <http://data.linkedmdb.org/resource/movie/performance> ?p .
  ?p <http://data.linkedmdb.org/resource/movie/performance_character>  ?pc .
  ?p <http://data.linkedmdb.org/resource/movie/performance_film> ?pf .  
  ?p <http://data.linkedmdb.org/resource/movie/performance_name> ?pn
}
