SELECT DISTINCT * WHERE {
  ?director <http://dbpedia.org/ontology/nationality> ?nat .
  ?film <http://dbpedia.org/ontology/director> ?director .
  ?movie <http://www.w3.org/2002/07/owl#sameAs> ?film .
  ?movie <http://data.linkedmdb.org/resource/movie/genre>  <http://data.linkedmdb.org/resource/film_genre/4> 
}
