SELECT DISTINCT * WHERE {
  ?film <http://dbpedia.org/ontology/budget> ?b .
  ?film <http://dbpedia.org/ontology/director> ?d .
  ?movie <http://www.w3.org/2002/07/owl#sameAs> ?film .
  ?movie <http://data.linkedmdb.org/resource/movie/sequel> ?s
}
