#!/bin/bash

cd /home/roott/federatedOptimizer/code

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/Drugbank/statisticsDrugbank_is_reduced10000CS /home/roott/fedBenchData/Drugbank/statisticsDrugbank_io_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_is_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_io_reduced10000CS /home/roott/fedBenchData/Drugbank/statisticsDrugbank_css_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_css_reduced10000CS /home/roott/fedBenchData/cps_Drugbank_DBpedia_reduced10000CS_MIP /home/roott/fedBenchData/cps_DBpedia_Drugbank_reduced10000CS_MIP > outputObtainHierarchicalCharacterizationDrugbankDBpedia 2> errorObtainHierarchicalCharacterizationDrugbankDBpedia

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/DBpedia/statisticsDBpedia_is_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_io_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_is_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_io_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_css_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_css_reduced10000CS /home/roott/fedBenchData/cps_DBpedia_ChEBI_reduced10000CS_MIP /home/roott/fedBenchData/cps_ChEBI_DBpedia_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsDBpediaChEBI 2> errorAddInterDatasetLinksMIPsDBpediaChEBI

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/KEGG/statisticsKEGG_is_reduced10000CS /home/roott/fedBenchData/KEGG/statisticsKEGG_io_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_is_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_io_reduced10000CS /home/roott/fedBenchData/KEGG/statisticsKEGG_css_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_css_reduced10000CS /home/roott/fedBenchData/cps_KEGG_DBpedia_reduced10000CS_MIP /home/roott/fedBenchData/cps_DBpedia_KEGG_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsKEGGDBpedia 2> errorAddInterDatasetLinksMIPsKEGGDBpedia

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/Drugbank/statisticsDrugbank_is_reduced10000CS /home/roott/fedBenchData/Drugbank/statisticsDrugbank_io_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_is_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_io_reduced10000CS /home/roott/fedBenchData/Drugbank/statisticsDrugbank_css_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_css_reduced10000CS /home/roott/fedBenchData/cps_Drugbank_Geonames_reduced10000CS_MIP /home/roott/fedBenchData/cps_Geonames_Drugbank_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsDrugbankGeonames 2> errorAddInterDatasetLinksMIPsDrugbankGeonames

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/Geonames/statisticsGeonames_is_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_io_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_is_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_io_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_css_reduced10000CS /home/roott/fedBenchData/ChEBI/statisticsChEBI_css_reduced10000CS /home/roott/fedBenchData/cps_Geonames_ChEBI_reduced10000CS_MIP /home/roott/fedBenchData/cps_ChEBI_Geonames_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsGeonamesChEBI 2> errorAddInterDatasetLinksMIPsGeonamesChEBI

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/KEGG/statisticsKEGG_is_reduced10000CS /home/roott/fedBenchData/KEGG/statisticsKEGG_io_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_is_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_io_reduced10000CS /home/roott/fedBenchData/KEGG/statisticsKEGG_css_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_css_reduced10000CS /home/roott/fedBenchData/cps_KEGG_Geonames_reduced10000CS_MIP /home/roott/fedBenchData/cps_Geonames_KEGG_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsGeonamesKEGG 2> errorAddInterDatasetLinksMIPsGeonamesKEGG

/usr/bin/time -f "%e %P %t %M" java addInterDatasetLinksMIPs /home/roott/fedBenchData/DBpedia/statisticsDBpedia_is_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_io_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_is_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_io_reduced10000CS /home/roott/fedBenchData/DBpedia/statisticsDBpedia_css_reduced10000CS /home/roott/fedBenchData/Geonames/statisticsGeonames_css_reduced10000CS /home/roott/fedBenchData/cps_DBpedia_Geonames_reduced10000CS_MIP /home/roott/fedBenchData/cps_Geonames_DBpedia_reduced10000CS_MIP > outputAddInterDatasetLinksMIPsGeonamesDBpedia 2> errorAddInterDatasetLinksMIPsGeonamesDBpedia

